name: Swift

on: [push]

jobs:
  build:

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
        with:
          swift-version: "5.5.0"
      - name: Get swift version
        run: swift --version 
      - name: Build
        run: swift build
      - name: Run tests
        run: swift test
